// login
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// logout
export const LOGOUT = 'LOGOUT'

// fetch meters
export const FETCH_METER_DATA_START = 'FETCH_METER_DATA_START'
export const FETCH_METER_DATA_SUCCESS = 'FETCH_METER_DATA_SUCCESS'
export const FETCH_METER_DATA_FAILURE = 'FETCH_METER_DATA_FAILURE'

// upload meter reading
export const UPLOAD_READING_START = 'UPLOAD_READING_START'
export const UPLOAD_READING_SUCCESS = 'UPLOAD_READING_SUCCESS'
export const UPLOAD_READING_FAILURE = 'UPLOAD_READING_FAILURE'

// fetch meter reading data
export const FETCH_READINGS_START = 'FETCH_READINGS_START'
export const FETCH_READINGS_SUCCESS = 'FETCH_READINGS_SUCCESS'
export const FETCH_READINGS_FAILURE = 'FETCH_READINGS_FAILURE'

// set meter reading
export const SET_METER_READING_START = 'SET_METER_READING_START'
export const SET_METER_READING_SUCCESS = 'SET_METER_READING_SUCCESS'
export const SET_METER_READING_FAILURE = 'SET_METER_READING_FAILURE'
